### ISSUE TITLE
From CLA Assistant to Contributor Assistant

### ISSUE THREAD

**Issue by doraschletz** [contributor-assistant/contributor-assistant#34]
This issue shall be raised on repo: https://github.com/cla-assistant/cla-assistant. We just draft it here.  
 
## BREAKING NEWS :)  

We are happy that so many of you are using the classic version of the [CLA Assistant](https://github.com/cla-assistant/cla-assistant). However, this service will not be maintained forever, as we are developing a simplified version.  

**We are excited to introduce and welcome you to the [Contributor Assistant](https://github.com/cla-assistant/contributor-assistant) and we encourage you to try it out soon.**

### **What will happen to the CLA assistant?**
We see a lot of value in the increasing decentralization. As the classical CLA Assistant does not support decentralization to the extent as the Contributor Assistant does, we think it is a good idea to actively encourage you to look into the [Contributor Assistant](https://github.com/cla-assistant/contributor-assistant).   
We have decided that in the long term we will not support the classic CLA Assistant anymore. This means that we will stop maintaining and updating the original CLA assistant. But don’t worry if you are already using this version. We will not take the service offline and the old repositories will remain at least until early 2022. Yet, there will be no updates or improvements made. Therefore we recommend to you to switch to the new Contributor Assistant and to raise issues on the Contributor Assistant in case you find any major feature gaps....  
If you still want to improve the classic offering and provide it as a free hosted solution for the whole open source community, feel free to spin up your own instance to grant this service.

### **Benefits of the new Contributor Assistant**
**With the new Contributor Assistant it is our main goal to update the technology, simplify the maintenance, and broaden its scope:**

In order to progress in this development and go further, we've decided to take advantage of GitHub's new service "GitHub Actions". With GitHub Actions, we believe to make the processes even easier to handle and operate, as there is no need for a backend. With GitHub Actions, there is no central server, which will minimize the maintenance work. GitHub guarantees stable and performant checks, as well as updates of the PR's CLA status. There also is no central database. This means that you have full control over the data and are flexible in your decision of where to store the signatures.

We want to broaden the scope by introducing new features like reward mechanisms, code quality checks, automated Slack-, Telegram-, and Discord notifications etc. 

The Contributor Assistant leverages latest most promising technologies like the Deno RTE. Deno is a secure runtime environment (similar to node) for JavaScript and TypeScript. It can e.g. import modules via https from everywhere on the web.

All the benefits at a glance:
- Updated to latest technologies
- Leveraging Deno runtime
- Easier to maintain
- Decentralized
- Reward System via the Contributor Assistant Coin
- Automated Slack-, Telegram-, and Discord notifications
- Code Quality Checks
- You can adjust Comment and PR Status texts according to your need
- You can use it for other documents e.g. Developer Certificate of Origin 

### **History Regarding The classic CLA assistant** 
Since 2014 we have provided the CLA assistant as an open-source project and a free hosted offering for the whole development community. So far, the hosted offering alone has helped more than **831** GitHub organizations and **7.330** GitHub repositories to manage their Contributor License Agreement in an easy non-disruptive way. With the help of the CLA assistant more than **133.075** Contributor License Agreements have already been signed with a single click.
We are happy about those achievements. The CLA Assistant has helped to fulfill our vision to "Make the world run better and improve people's lives" by making developers' lives a bit easier :)

**Comment by michael-spengler** [comment]
closing this issue as the OSPO team decided to continue maintaining the CLA Assistant Classic via https://github.com/cla-assistant/cla-assistant due to the need for org wide configuration options... which are not (yet) there in the github action based solutions.
